server:
  port: 8761
spring:
  application:
    name: eureka-server
  security:
    basic:
      enabled: false
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
